### ISSUE TITLE
ionic 1 support?

### ISSUE THREAD

**Issue by mysticmetal** [hitmacreed/Cordova-Plugin-Modern-Browser#2]
great job. how to make it work with ionic1 or angularjs project?

**Comment by hitmacreed** [comment]
@mysticmetal  Hi , at this moment i wont give support to ionic 1 because:
- To old ,
- Some features wont work,
- Android compatibility.

**Comment by hitmacreed** [comment]
Hi @mysticmetal  , at this moment i wont give support to ionic 1 sry :(
